### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Metaphor31** [fehmicansaglam/progressed.io#19]
HI Aarni, I am trying to use cryCompare (Python wrapper for Crypto Compare public API) , 

I have seen that you worked on this two, 

Could you please help me to get all data for only one exchange ? I want to get data from all exchanges separtely. 
Could you please reply here or email me : alex.gordonab@gmail.com thanks

Thank you, 

Alex

**Comment by fehmicansaglam** [comment]
Unrelated.
