### ISSUE TITLE
Service no longer available

### ISSUE THREAD

**Issue by kyosuke80** [fehmicansaglam/progressed.io#21]
I found out today that the usual url is no longer available.
There was any change on it?

**Comment by vincent27hugh** [comment]
Me too. Is there any problem?

**Comment by fehmicansaglam** [comment]
Yes, the service is down. I couldn't access to the droplet using password. I have to use my personal laptop which has my ssh keys. Unfortunately this will take at least 7 more hours.

**Comment by fehmicansaglam** [comment]
I've switched to a new droplet. The service is up but it will take some time for DNS caches to be updated. The new IP is 165.227.132.24.

**Comment by fehmicansaglam** [comment]
I've also setup monitoring and alerts. Sorry for the inconvenience. I'm closing this ticket right now.
