### ISSUE TITLE
feature request: percentages bigger than 100%

### ISSUE THREAD

**Issue by r-lyeh** [fehmicansaglam/progressed.io#8]
Hello there,

I am using your badges into https://github.com/r-lyeh/scriptorium and they look nice. Congrats : )
However, do you think you can add support to percentages higher than 100? Like, say, 2300%
To achieve this:
- Label should read 2300%
- Color should be green
- Bar should be filled completely

As you can see in my repo, I would like to support relative percentages as well : )
Keep up the good work,
- r-lyeh

**Comment by r-lyeh** [comment]
Additionally, negative percentages, like -200% should be empty (similar to 0%)

**Comment by fehmicansaglam** [comment]
@r-lyeh what's the point of percentages greater than 100?

**Comment by r-lyeh** [comment]
for example, i want to showcase relative speed between A and B.
if B is x2 times faster than A, then B speed is 200% of A.

**Comment by fehmicansaglam** [comment]
I see. Allowing more than 3 digits may produce width and alignment problems. What about the ability of changing the `%` character? Then you can use 2X or 3x or anything you want.

**Comment by r-lyeh** [comment]
I can still use ![image](http://progressed.io/bar/100?title=2x) but looks a bit off to me : )

**Comment by r-lyeh** [comment]
forgot to say that the x/X is a nice workaround that might work : )

**Comment by fehmicansaglam** [comment]
I will try to release it tomorrow.

**Comment by r-lyeh** [comment]
:+1:

**Comment by fehmicansaglam** [comment]
Can you try smth like this? http://progressed.io/bar/3?scale=4&title=mark&suffix=X

**Comment by r-lyeh** [comment]
it seems to work. i dont get the purpose of the scale stuff though : ) 
suffix and the new [0-999] range will be enough I guess. thx : D
