### ISSUE TITLE
progressed.io not available

### ISSUE THREAD

**Issue by gesellix** [fehmicansaglam/progressed.io#9]
Hi, thanks for your nice progress bar service - sadly the server seems to be unavailable for the past days. Did you shut it down intentionally?

**Comment by r-lyeh** [comment]
yep, +1. thanks for the service :) the service has been on/off during the past days.
it is more noticeable when you have lots of badges ( https://github.com/r-lyeh/scriptorium ).

**Comment by fehmicansaglam** [comment]
Sorry for the late reply. I think there is a problem with the DO service. I am going to solve it in a couple of minutes.

**Comment by fehmicansaglam** [comment]
It is up now.

**Comment by r-lyeh** [comment]
:clap: thx

**Comment by cssmagic** [comment]
Sorry. Seems unavailable again. :sob:

**Comment by fehmicansaglam** [comment]
Sorry, it is up now.

**Comment by cssmagic** [comment]
Thanks! :+1:
